sudo: required

language: generic

services:
  - docker

before-install:
  - echo "start creating an image with dockerfile"
  - docker build -t ted/docker-react-app -f Dockerfile .

script:
  - docker run -e CI=true ted/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
